#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "python"
    style = "powerline"
    display_mode = "always"
    powerline_symbol = ""
    foreground = "white"
    background = "transparent"
    template = "({{ .Venv }}) "

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    alias = 'Git'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    type = 'executiontime'
    alias = 'ExTime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = ' {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '➜'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  # {{ .Segments.Executiontime.FormattedMs }} | 
  template = '<blue>{{.PWD}}</>{{ if .Segments.Contains "Git" }} <white>{{ .Segments.Git.HEAD }}</>{{ end }} <yellow>^{{ .Segments.ExTime.FormattedMs }}</> ➜ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '➜➜ '
