[general]
import = [
   "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[env]
term = "xterm-256color"

[terminal.shell]
program = "/bin/bash"
args = ["-c", "~/.scripts/tmux_chooser.sh"]

[window]
# decorations = "None"
opacity = 1
dimensions = { columns = 90, lines = 30}
dynamic_title = true

[window.padding]
x = 10
y = 10

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true
