#!/bin/sh

# Exit if not in a tmux session or no arguments are provided
[ -z "$TMUX" ] && exit
[ "$#" -eq 1 ] || exit 1

newstyle="$1"

# Set the new status-style
tmux set-option -g status-style "$newstyle"

# Wait for the parent process (tmux) to exit, then reload tmux configuration
( tail --pid="$PPID" -f /dev/null
  tmux source-file ~/.tmux.conf ) &
